name: Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "libottorom" # Insert your Heroku app name here.
          heroku_email: "codinglittleshogi@gmail.com" # Insert your Heroku email here.
          usedocker: true
          docker_heroku_process_type: "worker"
